#'
#' @title Set option parameters for [sb_sync_event()]
#'
#' @param interactive_mode If TRUE, all messages are printed to the console.
#' If FALSE, they are suppressed. The idea is that `interactive_mode` should be
#' set to FALSE in automated environments to ensure logs aren't clogged up with
#' progress messages.
#' @param include_user_data If TRUE, information like the athlete's full
#' name (i.e. about) is attached to the exported data frame. Setting this to
#' FALSE can improve query performance since [sb_get_event()] doesn't need to
#' make an extra API call to grab the user data.
#' @param include_missing_user If TRUE, includes users who have not recorded
#' data in that form as rows of NA values.
#' @param guess_col_type If TRUE, [sb_get_event()] uses [readr::type_convert()]
#' to guess the column types of the exported data frame. If FALSE, all columns
#' will come through as character.
#' @param include_uuid If TRUE, each athlete's user-defined UUID
#' (universally unique identifier) is attached to the exported data frame.
#' Note, this is different to user_id, which is automatically generated by
#' Smartabase.
#' @param cache_user Logical. If `TRUE`, the result of `sb_get_user()`
#' will be cached on the local machine and reused within the current R session,
#' up to the timeout specified by `cache_user_timeout`. All of the export
#' functions (e.g. `sb_get_event()`, `sb_sync_event()` etc.) call
#' `sb_get_user()` internally, so caching is recommended given that retrieving
#' the user data can be
#' \itemize{
#'   \item Can be computationally intensive on large sites
#'   \item User data is slow-changing and unlike to change in a given R session
#' }
#' @param cache_user_timeout Numeric. Duration (in seconds) that cached user
#' data remains valid. After this timeout, the data will be refreshed from
#' the API. Note that cached results are only stored for the current R session.
#'
#' @returns A list of options with class = "sb_export_option"
#' @export
#'
#' @family export option helpers
#' @seealso
#' [sb_get_event_option()]
#' [sb_get_user_option()]
#' [sb_get_profile_option()]
#' [sb_get_group_option()]
#'
#' @examples
#' \dontrun{
#' # Calling the function with no arguments returns all the defaults
#' sb_sync_event_option()
#'
#' # Specifying specific arguments will alter those arguments alone while still
#' # returning the other defaults
#' sb_sync_event_option(guess_col_type = FALSE, interactive_mode = FALSE)
#' }
sb_sync_event_option <- function(
    interactive_mode = TRUE,
    include_user_data = TRUE,
    include_missing_user = FALSE,
    guess_col_type = TRUE,
    include_uuid = FALSE,
    cache_user = TRUE,
    cache_user_timeout = 1800
) {
  structure(
    class = "sb_export_option",
    list(
      interactive_mode = interactive_mode,
      include_user_data = include_user_data,
      include_missing_user = include_missing_user,
      guess_col_type = guess_col_type,
      include_uuid = include_uuid,
      cache_user = cache_user,
      cache_user_timeout = cache_user_timeout
    )
  )
}


#' @title Set option parameters for [sb_get_event()]
#'
#' @inheritParams sb_sync_event_option
#' @param download_attachment If TRUE, will download any files that are
#' included in the form via a file upload field.
#'
#' @returns A list of options with class = "sb_export_option"
#' @export
#'
#' @family export option helpers
#' @seealso
#' [sb_sync_event_option()]
#' [sb_get_user_option()]
#' [sb_get_profile_option()]
#' [sb_get_group_option()]
#'
#' @examples
#' \dontrun{
#' # Calling the function with no arguments returns all the defaults
#' sb_get_event_option()
#'
#' # Specifying specific arguments will alter those arguments alone while still
#' # returning the other defaults
#' sb_get_event_option(guess_col_type = FALSE, interactive_mode = FALSE)
#' }
sb_get_event_option <- function(
    interactive_mode = TRUE,
    include_user_data = TRUE,
    download_attachment = FALSE,
    include_missing_user = FALSE,
    guess_col_type = TRUE,
    include_uuid = FALSE,
    cache_user = TRUE,
    cache_user_timeout = 1800
) {
  structure(
    class = "sb_export_option",
    list(
      interactive_mode = interactive_mode,
      include_user_data = include_user_data,
      download_attachment = download_attachment,
      include_missing_user = include_missing_user,
      guess_col_type = guess_col_type,
      cache_user = cache_user,
      cache_user_timeout = cache_user_timeout
    )
  )
}


#' @title Set option parameters for [sb_get_profile()]
#'
#' @inheritParams sb_sync_event_option
#'
#' @returns A list of options with class = "sb_export_option"
#' @export
#'
#' @family export option helpers
#' @seealso
#' [sb_get_event_option()]
#' [sb_sync_event_option()]
#' [sb_get_user_option()]
#' [sb_get_group_option()]
#'
#' @examples
#' \dontrun{
#' # Calling the function with no arguments returns all the defaults
#' sb_get_profile_option()
#'
#' # Specifying specific arguments will alter those arguments alone while still
#' # returning the other defaults
#' sb_get_profile_option(guess_col_type = FALSE, interactive_mode = FALSE)
#' }
sb_get_profile_option <- function(
    interactive_mode = TRUE,
    include_user_data = TRUE,
    include_missing_user = FALSE,
    guess_col_type = TRUE,
    include_uuid = FALSE,
    cache_user = TRUE,
    cache_user_timeout = 1800
) {
  structure(
    class = "sb_export_option",
    list(
      interactive_mode = interactive_mode,
      include_user_data = include_user_data,
      include_missing_user = include_missing_user,
      guess_col_type = guess_col_type,
      include_uuid = include_uuid,
      cache_user = cache_user,
      cache_user_timeout = cache_user_timeout
    )
  )
}


#' @title Set option parameters for [sb_get_event()]
#'
#' @inheritParams sb_sync_event_option
#' @param include_all_cols If FALSE, only basic user information is included in
#' the returned data frame; e.g. user_id, username, about etc. If TRUE, extra
#' user information like phone, address and date of birth are also returned. If
#' only one user is returned, roles and groups information about that user is
#' included.
#'
#' @returns A list of options with class = "sb_export_option"
#' @export
#'
#' @family export option helpers
#' @seealso
#' [sb_get_event_option()]
#' [sb_sync_event_option()]
#' [sb_get_profile_option()]
#' [sb_get_group_option()]
#'
#' @examples
#' \dontrun{
#' # Calling the function with no arguments returns all the defaults
#' sb_get_user_option()
#'
#' # Specifying specific arguments will alter those arguments alone while still
#' # returning the other defaults
#' sb_get_user_option(guess_col_type = FALSE, interactive_mode = FALSE)
#' }
sb_get_user_option <- function(
    interactive_mode = TRUE,
    include_all_cols = FALSE,
    include_missing_user = FALSE,
    guess_col_type = TRUE,
    cache_user = TRUE,
    cache_user_timeout = 1800
) {
  structure(
    class = "sb_export_option",
    list(
      interactive_mode = interactive_mode,
      include_all_cols = include_all_cols,
      include_missing_user = include_missing_user,
      guess_col_type = guess_col_type,
      cache_user = cache_user,
      cache_user_timeout = cache_user_timeout
    )
  )
}


#' @title Set option parameters for [sb_get_group()]
#'
#' @inheritParams sb_sync_event_option
#'
#' @returns A list of options with class = "sb_export_option"
#' @export
#'
#' @family export option helpers
#' @seealso
#' [sb_get_event_option()]
#' [sb_sync_event_option()]
#' [sb_get_user_option()]
#' [sb_get_profile_option()]
#'
#' @examples
#' \dontrun{
#' # Calling the function with no arguments returns all the defaults
#' sb_get_group_option()
#'
#' # Specifying specific arguments will alter those arguments alone while still
#' # returning the other defaults
#' sb_get_group_option(guess_col_type = FALSE, interactive_mode = FALSE)
#' }
sb_get_group_option <- function(
    guess_col_type = TRUE,
    interactive_mode = TRUE
) {
  structure(
    class = "sb_export_option",
    list(
      guess_col_type = guess_col_type,
      interactive_mode = interactive_mode
    )
  )
}


#' @title Set option parameters for [sb_get_license_audit()]
#'
#' @param interactive_mode If TRUE, all messages are printed to the console.
#' If FALSE, they are suppressed. The idea is that `interactive_mode` should be
#' set to FALSE in automated environments to ensure logs aren't clogged up with
#' progress messages.
#' @param cache_audit Logical. If `TRUE`, the result of [sb_get_license_audit()]
#' will be cached on the local machine and reused within the current R session,
#' up to the timeout specified by `cache_audit_timeout`.
#' Caching is recommended because retrieving the license audit:
#' \itemize{
#'   \item Can be computationally intensive on large sites
#'   \item License audit data is slow-changing and unlike to change in a given
#'   R session
#' }
#'
#' @param cache_audit_timeout Numeric. Duration (in seconds) that a cached audit
#' result remains valid. After this timeout, the data will be refreshed from
#' the API. Note that cached results are only stored for the current R session.
#'
#' @returns A list of options with class = "sb_export_option"
#' @export
#'
#' @family export option helpers
#' @seealso
#' [sb_get_event_option()]
#' [sb_sync_event_option()]
#' [sb_get_user_option()]
#' [sb_get_profile_option()]
#'
#' @examples
#' \dontrun{
#' # Calling the function with no arguments returns all the defaults
#' sb_get_license_audit_option()
#'
#' # Specifying specific arguments will alter those arguments alone while still
#' # returning the other defaults
#' sb_get_license_audit_option(cache_audit = TRUE)
#' }
sb_get_license_audit_option <- function(
    interactive_mode = TRUE,
    cache_audit = TRUE,
    cache_audit_timeout = 1800
) {
  structure(
    class = "sb_export_option",
    list(
      interactive_mode = interactive_mode,
      cache_audit = cache_audit,
      cache_audit_timeout = cache_audit_timeout
    )
  )
}
