#'
#' @title Set option parameters for [sb_sync_event()]
#'
#' @param interactive_mode If TRUE, all messages are printed to the console.
#' If FALSE, they are suppressed. The idea is that `interactive_mode` should be
#' set to FALSE in automated environments to ensure logs aren't clogged up with
#' progress messages.
#' @param include_user_data If TRUE, information like the athlete's full
#' name (i.e. about) is attached to the exported data frame. Setting this to
#' FALSE can improve query performance since [sb_get_event()] doesn't need to
#' make an extra API call to grab the user data.
#' @param cache If TRUE, login token and user details are cached once per
#' session. Similar to `include_user_data`, caching can have performance
#' benefits when the user data set is large, such as on large Smartabase sites
#' with thousands of users. To invalidate the cache, restart your R session.
#' @param include_missing_user If TRUE, includes users who have not recorded
#' data in that form as rows of NA values.
#' @param guess_col_type If TRUE, [sb_get_event()] uses [readr::type_convert()]
#' to guess the column types of the exported data frame. If FALSE, all columns
#' will come through as character.
#' @param include_uuid If TRUE, each athlete's user-defined UUID
#' (universally unique identifier) is attached to the exported data frame.
#' Note, this is different to user_id, which is automatically generated by
#' Smartabase.
#'
#' @return A list of options with class = "sb_export_option"
#' @export
#'
#' @family export option helpers
#' @seealso
#' [sb_get_event_option()]
#' [sb_get_user_option()]
#' [sb_get_profile_option()]
#' [sb_get_group_option()]
#'
#' @examples
#' \dontrun{
#' # Calling the function with no arguments returns all the defaults
#' sb_sync_event_option()
#'
#' # Specifying specific arguments will alter those arguments alone while still
#' # returning the other defaults
#' sb_sync_event_option(guess_col_type = FALSE, interactive_mode = FALSE)
#' }
sb_sync_event_option <- function(
    interactive_mode = TRUE,
    include_user_data = TRUE,
    cache = TRUE,
    include_missing_user = FALSE,
    guess_col_type = TRUE,
    include_uuid = FALSE
) {
  structure(
    class = "sb_export_option",
    list(
      interactive_mode = interactive_mode,
      include_user_data = include_user_data,
      cache = cache,
      include_missing_user = include_missing_user,
      guess_col_type = guess_col_type,
      include_uuid = include_uuid
    )
  )
}


#' @title Set option parameters for [sb_get_event()]
#'
#' @inheritParams sb_sync_event_option
#' @param download_attachment If TRUE, will download any files that are
#' included in the form via a file upload field.
#'
#' @return A list of options with class = "sb_export_option"
#' @export
#'
#' @family export option helpers
#' @seealso
#' [sb_sync_event_option()]
#' [sb_get_user_option()]
#' [sb_get_profile_option()]
#' [sb_get_group_option()]
#'
#' @examples
#' \dontrun{
#' # Calling the function with no arguments returns all the defaults
#' sb_get_event_option()
#'
#' # Specifying specific arguments will alter those arguments alone while still
#' # returning the other defaults
#' sb_get_event_option(guess_col_type = FALSE, interactive_mode = FALSE)
#' }
sb_get_event_option <- function(
    interactive_mode = TRUE,
    include_user_data = TRUE,
    cache = TRUE,
    download_attachment = FALSE,
    include_missing_user = FALSE,
    guess_col_type = TRUE,
    include_uuid = FALSE
) {
  structure(
    class = "sb_export_option",
    list(
      interactive_mode = interactive_mode,
      include_user_data = include_user_data,
      cache = cache,
      download_attachment = download_attachment,
      include_missing_user = include_missing_user,
      guess_col_type = guess_col_type
    )
  )
}


#' @title Set option parameters for [sb_get_profile()]
#'
#' @inheritParams sb_sync_event_option
#'
#' @return A list of options with class = "sb_export_option"
#' @export
#'
#' @family export option helpers
#' @seealso
#' [sb_get_event_option()]
#' [sb_sync_event_option()]
#' [sb_get_user_option()]
#' [sb_get_group_option()]
#'
#' @examples
#' \dontrun{
#' # Calling the function with no arguments returns all the defaults
#' sb_get_profile_option()
#'
#' # Specifying specific arguments will alter those arguments alone while still
#' # returning the other defaults
#' sb_get_profile_option(guess_col_type = FALSE, interactive_mode = FALSE)
#' }
sb_get_profile_option <- function(
    interactive_mode = TRUE,
    include_user_data = TRUE,
    cache = TRUE,
    include_missing_user = FALSE,
    guess_col_type = TRUE,
    include_uuid = FALSE
) {
  structure(
    class = "sb_export_option",
    list(
      interactive_mode = interactive_mode,
      include_user_data = include_user_data,
      cache = cache,
      include_missing_user = include_missing_user,
      guess_col_type = guess_col_type,
      include_uuid = include_uuid
    )
  )
}


#' @title Set option parameters for [sb_get_event()]
#'
#' @inheritParams sb_sync_event_option
#' @param include_all_cols If FALSE, only basic user information is included in
#' the returned data frame; e.g. user_id, username, about etc. If TRUE, extra
#' user information like phone, address and date of birth are also returned. If
#' only one user is returned, roles and groups information about that user is
#' included.
#'
#' @return A list of options with class = "sb_export_option"
#' @export
#'
#' @family export option helpers
#' @seealso
#' [sb_get_event_option()]
#' [sb_sync_event_option()]
#' [sb_get_profile_option()]
#' [sb_get_group_option()]
#'
#' @examples
#' \dontrun{
#' # Calling the function with no arguments returns all the defaults
#' sb_get_user_option()
#'
#' # Specifying specific arguments will alter those arguments alone while still
#' # returning the other defaults
#' sb_get_user_option(guess_col_type = FALSE, interactive_mode = FALSE)
#' }
sb_get_user_option <- function(
    interactive_mode = TRUE,
    include_all_cols = FALSE,
    cache = TRUE,
    include_missing_user = FALSE,
    guess_col_type = TRUE
) {
  structure(
    class = "sb_export_option",
    list(
      interactive_mode = interactive_mode,
      include_all_cols = include_all_cols,
      cache = cache,
      include_missing_user = include_missing_user,
      guess_col_type = guess_col_type
    )
  )
}


#' @title Set option parameters for [sb_get_group()]
#'
#' @inheritParams sb_sync_event_option
#'
#' @return A list of options with class = "sb_export_option"
#' @export
#'
#' @family export option helpers
#' @seealso
#' [sb_get_event_option()]
#' [sb_sync_event_option()]
#' [sb_get_user_option()]
#' [sb_get_profile_option()]
#'
#' @examples
#' \dontrun{
#' # Calling the function with no arguments returns all the defaults
#' sb_get_group_option()
#'
#' # Specifying specific arguments will alter those arguments alone while still
#' # returning the other defaults
#' sb_get_group_option(guess_col_type = FALSE, interactive_mode = FALSE)
#' }
sb_get_group_option <- function(
    guess_col_type = TRUE,
    interactive_mode = TRUE
) {
  structure(
    class = "sb_export_option",
    list(
      guess_col_type = guess_col_type,
      interactive_mode = interactive_mode
    )
  )
}
