#' @title
#' Insert event data
#'
#' @description
#' `sb_insert_event()` imports a data frame into a Smartabase event form using
#' the Smartabase API. It requires the user to input a data frame, a valid
#' Smartabase event form name, url and credentials.
#'
#' For more details see the help vignette:
#' \code{vignette("exporting-data", package = "smartabaseR")}
#'
#' @section start_date / end_date / start_time / end_time columns:
#' When uploading data to Smartabase, the API requires metadata about when the
#' event started and stopped. `sb_insert_event()` will first search for any
#' columns in the data named "start_time" and "end_time", which must have
#' values in h:mm AM or h:mm PM format.
#'
#' If those columns do not exist, `start_time` and `end_time` will be set to
#' the current time and one hour after the current time, respectively.
#'
#' Likewise, `sb_insert_event()` will also search for any columns named
#' "start_date" or "end_date", which must have values formatted as dd/mm/YYYY.
#' If those columns do not exist, both `start_date` and `end_date` will be set
#' to the current date (unless the difference between `start_time` and
#' `end_time` spans midnight, in which case the `end_date` will be set to the
#' current date plus one day).
#'
#' @section Options:
#' There are also a range extra options than can be supplied to the `option`
#' argument, including options for setting a different ID column and supplying
#' the names of table fields, among others.  In order to reduce argument clutter
#' in `sb_insert_event()`, all options must be generated by the
#' [sb_insert_event_option()] function. Please see [sb_insert_event_option()]
#' for more details.
#'
#' @param df Data to be imported to Smartabase
#' @param form Name of Smartabase event form
#' @param url Smartabase url e.g. "example.smartabase.com/site"
#' @param username Smartabase username
#' @param password Smartabase password
#' @param ... These dots are for future extensions and must be empty
#' @param option More options accessible via [sb_insert_event_option()] object
#'
#' @return Data frame with extra details about import status
#' @export
#'
#' @examples
#' \dontrun{
#' example_df <- dplyr::tibble(
#'   user_id = c(31813, 31819),
#'   `Body Weight pre training` = round(runif(2, 82, 92), 0),
#'   `Body Weight post training` = round(runif(2, 82, 92), 0),
#'   `Urine Colour` = round(runif(2, 1, 8), 0)
#' )
#' sb_insert_event(
#'   df = example_df,
#'   form = "Hydration",
#'   url = "example.smartabase.com/site",
#'   username = "john.smith",
#'   password = "example_password"
#' )
#' }
#'
#' @family export functions
#' @seealso
#' [sb_update_event()]
#' [sb_upsert_event()]
#' [sb_upsert_profile()]
sb_insert_event <- function(
    df,
    form,
    url,
    username,
    password,
    ...,
    option = sb_insert_event_option()
) {
  env <- rlang::current_env()
  .validate_import_df_class(df, env)
  .validate_table_field(df, option$table_field, env)
  .check_import_class(option, env)
  rlang::check_dots_used()
  df <- .remove_event_id(df)

  arg <- list(
    form = form,
    url = .validate_url(url),
    username = username,
    password = password,
    option = option,
    type = "event",
    update_event = FALSE,
    current_env = env,
    ...
  )

  .validate_id_col(df, arg)
  if (!is.null(arg$dev_mode)) {
    if (isTRUE(arg$dev_mode)) {
      return(arg)
    }
  }
  .import_handler(df, arg)
}


#' @title
#' Update profile data
#'
#' @description
#' `sb_update_event()` imports data frame into a Smartabase event form using
#' the Smartabase API. It requires the user to input a data frame, a valid
#' Smartabase event form name, url and credentials.
#'
#' If the data frame contains a profile record that already exists in
#' Smartabase, then that profile record is updated. The data frame must have an
#' `event_id` column that contains valid Smartabase event IDs.
#'
#' For more details see the help vignette:
#' \code{vignette("importing-data", package = "smartabaseR")}
#'
#' @section Options:
#' There are also a range extra options than can be supplied to the `option`
#' argument, including options for setting a different ID column and supplying
#' the names of table fields, among others.  In order to reduce argument clutter
#' in `sb_update_event()`, all options must be generated by the
#' [sb_update_event_option()] function. Please see [sb_update_event_option()]
#' for more details.
#'
#' @inheritParams sb_insert_event
#' @param option More options accessible via [sb_update_event_option()] object
#'
#' @return Data frame with extra details about import status
#'
#' @export
sb_update_event <- function(
    df,
    form,
    url,
    username,
    password,
    ...,
    option = sb_update_event_option()
) {
  env <- rlang::current_env()
  .validate_import_df_class(df, env)
  .check_import_class(option, env)
  rlang::check_dots_used()

  arg <- list(
    form = form,
    url = .validate_url(url),
    username = username,
    password = password,
    option = option,
    type = "event",
    update_event = TRUE,
    current_env = env,
    ...
  )

  .validate_id_col(df, arg)
  df <- .validate_update_df(df, env = arg$current_env)
  if (!is.null(arg$dev_mode)) {
    if (isTRUE(arg$dev_mode)) {
      return(arg)
    }
  }
  arg <- .get_cached_endpoint(arg)
  .import_handler(df, arg)
}



#' @title
#' Upsert event data
#'
#' @description
#' `sb_upsert_event()` imports data frame into a Smartabase event form using
#' the Smartabase API. It requires the user to input a data frame, a valid
#' Smartabase event form name, url and credentials.
#'
#' If the data frame contains an event that already exists in Smartabase, then
#' that event is updated. If the data frame contains an event does not exist
#' in Smartabase, then that event will be inserted as a new event.
#'
#' For more details see the help vignette:
#' \code{vignette("importing-data", package = "smartabaseR")}
#'
#' @section start_date / end_date / start_time / end_time columns:
#' When uploading data to Smartabase, the API requires metadata about when the
#' event started and stopped. `sb_upsert_event()` will first search for any
#' columns in the data named "start_time" and "end_time", which must have
#' values in h:mm AM or h:mm PM format.
#'
#' If those columns do not exist, `start_time` and `end_time` will be set to
#' the current time and one hour after the current time, respectively.
#'
#' Likewise, `sb_upsert_event()` will also search for any columns named
#' "start_date" or "end_date", which must have values formatted as dd/mm/YYYY.
#' If those columns do not exist, both `start_date` and `end_date` will be set
#' to the current date (unless the difference between `start_time` and
#' `end_time` spans midnight, in which case the `end_date` will be set to the
#' current date plus one day).
#'
#' @section Options:
#' There are also a range extra options than can be supplied to the `option`
#' argument, including options for setting a different ID column and supplying
#' the names of table fields, among others.  In order to reduce argument clutter
#' in `sb_upsert_event()`, all options must be generated by the
#' [sb_upsert_event_option()] function. Please see [sb_upsert_event_option()]
#' for more details.
#'
#' @inheritParams sb_insert_event
#' @param option More options accessible via [sb_upsert_event_option()] object
#'
#' @return Data frame with extra details about import status
#'
#' @export
sb_upsert_event <- function(
    df,
    form,
    url,
    username,
    password,
    ...,
    option = sb_insert_event_option()
) {
  env <- rlang::current_env()
     .validate_import_df_class(df, env)
  .check_import_class(option, env)
  rlang::check_dots_used()

  arg <- list(
    form = form,
    url = .validate_url(url),
    username = username,
    password = password,
    option = option,
    type = "event",
    update_event = TRUE,
    current_env = env,
    ...
  )

  .validate_id_col(df, arg)
  .validate_upsert_df(df, arg$current_env)
  if (!is.null(arg$dev_mode)) {
    if (isTRUE(arg$dev_mode)) {
      return(arg)
    }
  }
  arg <- .get_cached_endpoint(arg)
  .import_handler(df, arg)
}



#' @title
#' Upsert profile data
#'
#' @description
#' `sb_upsert_profile()` imports data frame into a Smartabase event form using
#' the Smartabase API. It requires the user to input a data frame, a valid
#' Smartabase event form name, url and credentials.
#'
#' If the data frame contains a profile record that already exists in
#' Smartabase, then that profile record is updated. If the data frame contains
#' a profile record that does not exist in Smartabase, then that profile record
#' will be inserted as a new profile record.
#'
#' For more details see the help vignette:
#' \code{vignette("importing-data", package = "smartabaseR")}
#'
#' @section Options:
#' There are also a range extra options than can be supplied to the `option`
#' argument, including options for setting a different ID column and supplying
#' the names of table fields, among others.  In order to reduce argument clutter
#' in `sb_upsert_profile()`, all options must be generated by the
#' [sb_upsert_profile_option()] function. Please see
#' [sb_upsert_profile_option()] for more details.
#'
#' @inheritParams sb_insert_event
#' @param option More options accessible via [sb_upsert_profile_option()] object
#'
#' @return Data frame with extra details about import status
#'
#' @export
sb_upsert_profile <- function(
    df,
    form,
    url,
    username,
    password,
    ...,
    option = sb_upsert_profile_option()
) {
  env <- rlang::current_env()
     .validate_import_df_class(df, env)
  .check_import_class(option, env)
  rlang::check_dots_used()
  df <- df %>% dplyr::mutate(row_num = dplyr::row_number())

  arg <- list(
    form = form,
    url = .validate_url(url),
    username = username,
    password = password,
    option = option,
    type = "profile",
    update_event = FALSE,
    current_env = env,
    ...
  )

  .validate_id_col(df, arg)
  if (!is.null(arg$dev_mode)) {
    if (isTRUE(arg$dev_mode)) {
      return(arg)
    }
  }
  arg <- .get_cached_endpoint(arg)
  .import_handler(df, arg)
}


